/**
 * Shared admin dashboard UI tokens (inline styles, consistent with index.css variables).
 */
import type React from 'react';

export const adminUi = {
  page: {
    maxWidth: 1280,
    margin: '0 auto',
    width: '100%',
    boxSizing: 'border-box' as const,
    paddingBottom: 36,
    paddingInline: 'clamp(12px, 2vw, 24px)',
  },
  pageHeader: {
    marginBottom: 24,
    paddingBottom: 16,
    borderBottom: '1px solid var(--admin-border)',
  },
  h1: {
    fontSize: '1.5rem',
    fontWeight: 600,
    letterSpacing: '-0.01em',
    color: 'var(--admin-text)',
    margin: 0,
    lineHeight: 1.25,
  },
  sub: {
    fontSize: '0.875rem',
    color: 'var(--admin-muted)',
    margin: '8px 0 0',
    lineHeight: 1.5,
    maxWidth: 720,
  },
  card: {
    background: 'linear-gradient(165deg, var(--admin-surface-raised, #fff) 0%, var(--admin-surface) 100%)',
    borderRadius: 12,
    border: '1px solid var(--admin-border)',
    boxShadow: 'var(--admin-shadow-sm)',
    padding: '24px',
    boxSizing: 'border-box' as const,
    transition: 'box-shadow 0.15s ease',
  },
  cardTitle: {
    fontSize: '1.125rem',
    fontWeight: 500,
    color: 'var(--admin-text)',
    marginBottom: 6,
  },
  cardSub: {
    fontSize: '0.875rem',
    color: 'var(--admin-muted)',
    fontWeight: 500,
    lineHeight: 1.45,
    marginBottom: 16,
  },
  toolbar: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  input: {
    minWidth: 180,
    flex: '1 1 200px',
    border: '1px solid var(--admin-border)',
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: '0.9375rem',
    background: 'var(--admin-surface-raised)',
    color: 'var(--admin-text)',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  select: {
    border: '1px solid var(--admin-border)',
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: '0.9375rem',
    background: 'var(--admin-surface-raised)',
    color: 'var(--admin-text)',
    cursor: 'pointer',
    minWidth: 140,
  },
  btn: {
    border: '1px solid var(--admin-border)',
    borderRadius: 10,
    background: 'var(--admin-surface-raised)',
    padding: '10px 16px',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: '0.875rem',
    color: 'var(--admin-text)',
    transition: 'background 0.15s, border-color 0.15s',
  },
  btnPrimary: {
    border: 'none',
    borderRadius: 10,
    background: 'var(--admin-primary)',
    color: '#fff',
    padding: '10px 18px',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: '0.875rem',
    boxShadow: '0 1px 2px rgba(37, 99, 235, 0.25)',
  },
  btnDanger: {
    border: '1px solid #fecaca',
    borderRadius: 8,
    background: '#fef2f2',
    color: '#b91c1c',
    padding: '6px 10px',
    cursor: 'pointer',
    fontSize: '0.75rem',
    fontWeight: 700,
  },
  btnMuted: {
    border: '1px solid var(--admin-border)',
    borderRadius: 8,
    background: 'var(--admin-bg)',
    padding: '6px 10px',
    cursor: 'pointer',
    fontSize: '0.75rem',
    fontWeight: 700,
    color: 'var(--admin-text)',
  },
  tableScroll: {
    border: '1px solid var(--admin-border)',
    borderRadius: 12,
    overflow: 'auto' as const,
    maxHeight: 'min(560px, 62vh)',
    background: 'linear-gradient(180deg, var(--admin-surface-raised) 0%, var(--admin-surface) 100%)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '0.875rem',
    minWidth: 560,
  },
  th: {
    textAlign: 'left' as const,
    padding: '12px 14px',
    background: 'var(--admin-th-bg)',
    color: 'var(--admin-muted)',
    fontWeight: 800,
    fontSize: '0.6875rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
    borderBottom: '1px solid var(--admin-border)',
    position: 'sticky' as const,
    top: 0,
    zIndex: 1,
    whiteSpace: 'nowrap' as const,
  },
  td: {
    padding: '12px 14px',
    borderBottom: '1px solid var(--admin-border-subtle)',
    color: 'var(--admin-text)',
    verticalAlign: 'middle' as const,
  },
  trHover: {
    cursor: 'pointer' as const,
    transition: 'background 0.12s',
  },
  empty: {
    padding: 28,
    textAlign: 'center' as const,
    color: 'var(--admin-muted)',
    fontSize: '0.875rem',
    fontWeight: 600,
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: 24,
    marginBottom: 24,
  },
  kpiCard: {
    background: 'linear-gradient(145deg, var(--admin-surface-raised) 0%, var(--admin-surface) 100%)',
    borderRadius: 12,
    padding: '20px',
    border: '1px solid var(--admin-border)',
    boxShadow: 'var(--admin-shadow-sm)',
    minHeight: 132,
    display: 'flex',
    flexDirection: 'column' as const,
    justifyContent: 'space-between',
    transition: 'box-shadow 0.15s ease',
  },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    borderRadius: 999,
    fontSize: '0.75rem',
    fontWeight: 700,
    background: 'var(--admin-bg-subtle)',
    border: '1px solid var(--admin-border)',
    color: 'var(--admin-text)',
    cursor: 'pointer' as const,
  },
};

export function mergeStyle(...parts: (React.CSSProperties | undefined | false)[]): React.CSSProperties {
  return Object.assign({}, ...parts.filter(Boolean) as React.CSSProperties[]);
}
