/**
 * Shared admin dashboard UI tokens (inline styles, consistent with index.css variables).
 */
import type React from 'react';

export const adminUi = {
  page: {
    maxWidth: 1400,
    margin: '0 auto',
    width: '100%',
    boxSizing: 'border-box' as const,
    paddingBottom: 32,
  },
  pageHeader: {
    marginBottom: 24,
    paddingBottom: 20,
    borderBottom: '1px solid var(--admin-border)',
  },
  h1: {
    fontSize: 'clamp(1.375rem, 2vw, 1.75rem)',
    fontWeight: 800,
    letterSpacing: '-0.03em',
    color: 'var(--admin-text)',
    margin: 0,
    lineHeight: 1.25,
  },
  sub: {
    fontSize: '0.9375rem',
    color: 'var(--admin-muted)',
    margin: '8px 0 0',
    lineHeight: 1.55,
    maxWidth: 720,
  },
  card: {
    background: 'var(--admin-surface)',
    borderRadius: 14,
    border: '1px solid var(--admin-border)',
    boxShadow: 'var(--admin-shadow-sm)',
    padding: '20px 22px',
    boxSizing: 'border-box' as const,
  },
  cardTitle: {
    fontSize: '0.8125rem',
    fontWeight: 800,
    color: 'var(--admin-text)',
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
    marginBottom: 4,
  },
  cardSub: {
    fontSize: '0.8125rem',
    color: 'var(--admin-muted)',
    fontWeight: 600,
    lineHeight: 1.45,
    marginBottom: 16,
  },
  toolbar: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 12,
    alignItems: 'center',
    marginBottom: 16,
  },
  input: {
    minWidth: 180,
    flex: '1 1 200px',
    border: '1px solid var(--admin-border)',
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: '0.9375rem',
    background: 'var(--admin-surface)',
    color: 'var(--admin-text)',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  select: {
    border: '1px solid var(--admin-border)',
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: '0.9375rem',
    background: 'var(--admin-surface)',
    color: 'var(--admin-text)',
    cursor: 'pointer',
    minWidth: 140,
  },
  btn: {
    border: '1px solid var(--admin-border)',
    borderRadius: 10,
    background: 'var(--admin-surface)',
    padding: '10px 16px',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: '0.875rem',
    color: 'var(--admin-text)',
    transition: 'background 0.15s, border-color 0.15s',
  },
  btnPrimary: {
    border: 'none',
    borderRadius: 10,
    background: 'var(--admin-primary)',
    color: '#fff',
    padding: '10px 18px',
    cursor: 'pointer',
    fontWeight: 700,
    fontSize: '0.875rem',
    boxShadow: '0 1px 2px rgba(37, 99, 235, 0.25)',
  },
  btnDanger: {
    border: '1px solid #fecaca',
    borderRadius: 8,
    background: '#fef2f2',
    color: '#b91c1c',
    padding: '6px 10px',
    cursor: 'pointer',
    fontSize: '0.75rem',
    fontWeight: 700,
  },
  btnMuted: {
    border: '1px solid var(--admin-border)',
    borderRadius: 8,
    background: 'var(--admin-bg)',
    padding: '6px 10px',
    cursor: 'pointer',
    fontSize: '0.75rem',
    fontWeight: 700,
    color: 'var(--admin-text)',
  },
  tableScroll: {
    border: '1px solid var(--admin-border)',
    borderRadius: 12,
    overflow: 'auto' as const,
    maxHeight: 'min(560px, 65vh)',
    background: 'var(--admin-surface)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '0.875rem',
    minWidth: 640,
  },
  th: {
    textAlign: 'left' as const,
    padding: '12px 14px',
    background: 'var(--admin-bg-subtle)',
    color: 'var(--admin-muted)',
    fontWeight: 800,
    fontSize: '0.6875rem',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.06em',
    borderBottom: '1px solid var(--admin-border)',
    position: 'sticky' as const,
    top: 0,
    zIndex: 1,
    whiteSpace: 'nowrap' as const,
  },
  td: {
    padding: '12px 14px',
    borderBottom: '1px solid var(--admin-border-subtle)',
    color: 'var(--admin-text)',
    verticalAlign: 'middle' as const,
  },
  trHover: {
    cursor: 'pointer' as const,
    transition: 'background 0.12s',
  },
  empty: {
    padding: 28,
    textAlign: 'center' as const,
    color: 'var(--admin-muted)',
    fontSize: '0.875rem',
    fontWeight: 600,
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: 16,
    marginBottom: 24,
  },
  kpiCard: {
    background: 'var(--admin-surface)',
    borderRadius: 14,
    padding: '18px 20px',
    border: '1px solid var(--admin-border)',
    boxShadow: 'var(--admin-shadow-sm)',
  },
  pill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 12px',
    borderRadius: 999,
    fontSize: '0.75rem',
    fontWeight: 700,
    background: 'var(--admin-bg-subtle)',
    border: '1px solid var(--admin-border)',
    color: 'var(--admin-text)',
    cursor: 'pointer' as const,
  },
};

export function mergeStyle(...parts: (React.CSSProperties | undefined | false)[]): React.CSSProperties {
  return Object.assign({}, ...parts.filter(Boolean) as React.CSSProperties[]);
}
